### PR TITLE
Fetch example

### PR DESCRIPTION
**Pull request by rvanheest**
fixes EASY-1099
#### When applied it will
- add a new example bag with fetch.txt
#### What needs to be done by @rvanheest before this PR can be merged?
- [x] test what goes wrong when this bag would have an empty file in its `fetch.txt`. Sometimes the file cannot be downloaded from [GitHub](https://github.com/DANS-KNAW/easy-sword2-dans-examples/tree/master/src/main/resources/fetch-files) and instead it gives a 503 Service Not Available error. Does this also happen with non-empty files? Should we include a 'wait-and-retry' policy in easy-sword2 for this?
- [x] test what goes wrong when this bag contains an empty file that is successfully fetched from GitHub. In these cases we get a 500 error from Fedora. Does this have to do with the file being empty (e.g. 0 bytes)? Should we do anything about this?
- [x] review the additions to the README. Are these still valid?
#### Where should the reviewer @DANS-KNAW/easy start?

This PR contains a new bag with a `fetch.txt`. Happy reading. Consider it all to be random sequences of characters 😉 
#### How should this be manually tested?
1. deploy https://github.com/DANS-KNAW/easy-sword2/pull/64 on deasy
2. follow the instructions in the README
3. you should be able to completely submit a bag into easy and view it in webapp
#### related pull requests on github

| repo | PR | note |
| --- | --- | --- |
| easy-sword2 | [PR#64](https://github.com/DANS-KNAW/easy-sword2/pull/64) | the example in this PR uses PR#64. merge/deploy this one first! |

### CODE REVIEW

**Comment by janvanmansum** [comment]
@rvanheest: A small correction: the error from Fedora is not 503 but 500. The 503 Service Not Available is what you are sometimes getting from GitHub.

**Comment by rvanheest** [comment]
@janvanmansum fixed it in the original text. Thanks!

**Comment by rvanheest** [comment]
``` scala
FedoraClient.addDatastream("easy-dataset:XXX", "MY_EMPTY_CONTENT") // fill in the name of an existing dataset
  .controlGroup("M")
  .versionable(false)
  .mimeType("text/plain")
  .dsLabel("file.txt")
  .content(new File("easy-ingest-flow/file.txt")) // make this empty file yourself
  .checksum("SHA-1")
  .execute(new FedoraClient(new FedoraCredentials("xxx", "xxx", "xxx"))) // fill in the fedora credentials
```

Given this code snippet I can confirm that fedora does not really like ingesting empty files. The result is as shown below. Should we create an issue for that?

```
Exception in thread "main" com.yourmediashelf.fedora.client.FedoraClientException: HTTP 500 Error: javax.ws.rs.WebApplicationException: org.fcrepo.server.errors.StreamWriteException: Error writing temp stream
    at org.fcrepo.server.rest.BaseRestResource.handleException(BaseRestResource.java:172)
    at org.fcrepo.server.rest.DatastreamResource.addOrUpdateDatastream(DatastreamResource.java:583)
    at org.fcrepo.server.rest.DatastreamResource.addDatastream(DatastreamResource.java:358)
    at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:175)
    at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:67)
    at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:163)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:111)
    at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:71)
    at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:111)
    at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:63)
    at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:689)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:647)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:638)
    at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:309)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:425)
    at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:590)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.fcrepo.server.security.servletfilters.FilterRestApiFlash.doFilter(FilterRestApiFlash.java:79)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:368)
    at org.fcrepo.server.security.jaas.AuthFilterJAAS.doFilter(AuthFilterJAAS.java:330)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
    at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:109)
    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:169)
    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:299)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.fcrepo.server.errors.StreamWriteException: Error writing temp stream
    at org.fcrepo.server.management.DefaultManagement.putTempStream(DefaultManagement.java:1312)
    at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.fcrepo.server.messaging.NotificationInvocationHandler.invoke(NotificationInvocationHandler.java:68)
    at com.sun.proxy.$Proxy11.putTempStream(Unknown Source)
    at org.fcrepo.server.management.ManagementModule.putTempStream(ManagementModule.java:497)
    at org.fcrepo.server.rest.DatastreamResource.addOrUpdateDatastream(DatastreamResource.java:465)
    ... 43 more
Caused by: java.lang.NullPointerException
    at org.fcrepo.server.utilities.StreamUtility.pipeStream(StreamUtility.java:128)
    at org.fcrepo.server.management.DefaultManagement.putTempStream(DefaultManagement.java:1303)
    ... 50 more

    at com.yourmediashelf.fedora.client.response.FedoraResponseImpl.<init>(FedoraResponseImpl.java:72)
    at com.yourmediashelf.fedora.client.response.DatastreamProfileResponse.<init>(DatastreamProfileResponse.java:44)
    at com.yourmediashelf.fedora.client.response.AddDatastreamResponse.<init>(AddDatastreamResponse.java:39)
    at com.yourmediashelf.fedora.client.request.AddDatastream.execute(AddDatastream.java:244)
    at nl.knaw.dans.easy.ingest_flow.EmptyFileInFedoraTest$.delayedEndpoint$nl$knaw$dans$easy$ingest_flow$EmptyFileInFedoraTest$1(EmptyFileInFedoraTest.scala:20)
    at nl.knaw.dans.easy.ingest_flow.EmptyFileInFedoraTest$delayedInit$body.apply(EmptyFileInFedoraTest.scala:7)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at nl.knaw.dans.easy.ingest_flow.EmptyFileInFedoraTest$.main(EmptyFileInFedoraTest.scala:7)
    at nl.knaw.dans.easy.ingest_flow.EmptyFileInFedoraTest.main(EmptyFileInFedoraTest.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by rvanheest** [comment]
Regarding the 503 error, I have found more evidence that this is a problem at GitHub. See also the image below. I just sent an email to GitHub; to be continued...

screen shot 2016-10-18 at 13 52 38

**Comment by janvanmansum** [comment]
Kind of ironic, as there shouldn't be too many bytes to read ...

I suppose you have already looked for [an explanation of the error message](https://info.varnish-software.com/blog/understanding-timeouts-varnish-cache).

**Comment by rvanheest** [comment]
**Status update on the issue with GitHub:** they just responded and asked for more clarification on whether downloading an empty file _always_ results in a `503` error, or whether this happens just _once in a while_.

**Comment by rvanheest** [comment]
**Another status update on the issue with GitHub:** they reached out again and asked for the output of the `curl` command below. The output can be found in https://gist.github.com/rvanheest/0786bff73ed6b6f1d2e9c4735d7788e1

```
curl -vvv https://raw.githubusercontent.com/DANS-KNAW/easy-sword2-dans-examples/master/src/main/resources/fetch-files/empty-file.txt -o /dev/null
```

**Review by janvanmansum — APPROVED** [review]
It works like a charm 👍 

The only thing that is a bit confusing now is that different names are used for the files in EASY than the actual file names. This is a feature, not a bug, but the way it is used in the examples is confusing, so I will create a new issue for that.

**Comment by rvanheest** [comment]
**Final update on the issue with GitHub:**

> Our team took a look, and we don't see anything out of the ordinary. We see the error of course, but we don't see something obvious on our end. We'll keep an eye for similar reports though, and investigate further if we have more data.

**My response:**

> Thanks again for your response. I’d love to hear when your team is diving into this some more! Until then we’ll either stay away from downloading these empty files or go ahead and implement a retry policy which might solve it on our end.

I guess we complete this issue here and move on. When implementing the retry policy (if we do that) we have a nice test case with this, I suppose!

**Pull request merged**
